name: Deploy Flask App to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Flask App via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ~
            if [ -d python-ci-cd ]; then
              echo \"Removing existing directory to ensure clean state...\"
              sudo rm -rf python-ci-cd
            fi
            git clone --branch main https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} python-ci-cd
            cd python-ci-cd
            ls -al
            python3 -m venv venv
            echo "➡️ Activate virtualenv"
            source venv/bin/activate

            echo "➡️ Install dependencies"
            pip install -r requirements.txt

            echo "➡️ Restart Flask service"
            sudo systemctl restart flaskapp
