# Deploy Flask app when code is pushed to main
name: Deploy Flask App to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted Linux runner

    steps:
      # Clone repository into runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # SSH into GCP VM and deploy
      - name: Deploy Flask App via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}        # VM public IP/DNS
          username: ${{ secrets.VM_USER }}   # VM username
          key: ${{ secrets.VM_SSH_KEY }}     # SSH private key
          port: ${{ secrets.SSH_PORT }}      # SSH port (usually 22)

          script: |
            set -e  # Stop on error

            cd ~

            # Remove old project folder
            if [ -d python-ci-cd ]; then
              sudo rm -rf python-ci-cd
            fi

            # Clone latest code from main branch
            git clone --branch main https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} python-ci-cd

            cd python-ci-cd

            python3 -m venv venv      # Create virtual environment
            source venv/bin/activate # Activate venv
            pip install -r requirements.txt  # Install dependencies

            sudo systemctl restart flaskapp  # Restart service
