name: Deploy Flask App to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SA_KEY }}

      - name: Deploy Flask App via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            APP_DIR="/home/pavan_kalyan_cloudambassadors_co/python-ci-cd"

            echo "➡️ Moving to app directory"
            cd "$APP_DIR"

            echo "➡️ Pull latest code"
            git fetch origin
            git reset --hard origin/main

            echo "➡️ Activate virtualenv"
            source venv/bin/activate

            echo "➡️ Install dependencies"
            pip install -r requirements.txt

            echo "➡️ Restart Flask service"
            sudo systemctl restart flaskapp
